""" Phase 5 Payroll Management

Revision ID: 07a111a0ba2e
Revises: 25bb9da99ec7
Create Date: 2026-08-22 14:38:59.001834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a111a0ba2e'
down_revision: Union[str, Sequence[str], None] = '25bb9da99ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('effective_from', sa.String(), nullable=False),
    sa.Column('effective_to', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('pay_frequency', sa.String(), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structures_employee_id'), 'salary_structures', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_structures_id'), 'salary_structures', ['id'], unique=False)
    op.create_table('payroll_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('payroll_month', sa.Integer(), nullable=False),
    sa.Column('payroll_year', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.String(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('payable_days', sa.Integer(), nullable=True),
    sa.Column('absent_days', sa.Integer(), nullable=True),
    sa.Column('leave_days', sa.Integer(), nullable=True),
    sa.Column('lop_days', sa.Integer(), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.Column('gross_earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lop_deduction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_pay', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'PROCESSED', 'FINALIZED', name='payrollstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'payroll_month', 'payroll_year', name='uix_employee_payroll_period')
    )
    op.create_index(op.f('ix_payroll_records_employee_id'), 'payroll_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_id'), 'payroll_records', ['id'], unique=False)
    op.create_table('salary_components',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('salary_structure_id', sa.String(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('component_type', sa.Enum('EARNING', 'DEDUCTION', name='componenttype'), nullable=False),
    sa.Column('calculation_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('taxable', sa.Boolean(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_components_id'), 'salary_components', ['id'], unique=False)
    op.create_index(op.f('ix_salary_components_salary_structure_id'), 'salary_components', ['salary_structure_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payroll_record_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('payslip_number', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('document_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_record_id'),
    sa.UniqueConstraint('payslip_number')
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_salary_components_salary_structure_id'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_id'), table_name='salary_components')
    op.drop_table('salary_components')
    op.drop_index(op.f('ix_payroll_records_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_employee_id'), table_name='payroll_records')
    op.drop_table('payroll_records')
    op.drop_index(op.f('ix_salary_structures_id'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_employee_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    # ### end Alembic commands ###
