""" Phase 8 Offboarding and Separation

Revision ID: 2e66eb81c306
Revises: 04a9ffa2adf8
Create Date: 2026-08-22 15:03:35.495340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e66eb81c306'
down_revision: Union[str, Sequence[str], None] = '04a9ffa2adf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resignation_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('requested_date', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='resignationstatus'), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resignation_requests_employee_id'), 'resignation_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_resignation_requests_id'), 'resignation_requests', ['id'], unique=False)
    op.create_table('separation_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('resignation_request_id', sa.String(), nullable=True),
    sa.Column('separation_date', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLEARANCE_IN_PROGRESS', 'SETTLEMENT_PENDING', 'COMPLETED', 'CANCELLED', name='separationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['resignation_request_id'], ['resignation_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('resignation_request_id')
    )
    op.create_index(op.f('ix_separation_records_id'), 'separation_records', ['id'], unique=False)
    op.create_table('clearance_checklists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('separation_record_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('clearance_type', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'NOT_APPLICABLE', name='clearancestatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['separation_record_id'], ['separation_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clearance_checklists_id'), 'clearance_checklists', ['id'], unique=False)
    op.create_index(op.f('ix_clearance_checklists_separation_record_id'), 'clearance_checklists', ['separation_record_id'], unique=False)
    op.create_table('final_settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('separation_record_id', sa.String(), nullable=False),
    sa.Column('payroll_record_id', sa.String(), nullable=True),
    sa.Column('final_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lop_deduction', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_payments', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_settlement', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSED', 'PAID', name='settlementstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ),
    sa.ForeignKeyConstraint(['separation_record_id'], ['separation_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('separation_record_id')
    )
    op.create_index(op.f('ix_final_settlements_id'), 'final_settlements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_settlements_id'), table_name='final_settlements')
    op.drop_table('final_settlements')
    op.drop_index(op.f('ix_clearance_checklists_separation_record_id'), table_name='clearance_checklists')
    op.drop_index(op.f('ix_clearance_checklists_id'), table_name='clearance_checklists')
    op.drop_table('clearance_checklists')
    op.drop_index(op.f('ix_separation_records_id'), table_name='separation_records')
    op.drop_table('separation_records')
    op.drop_index(op.f('ix_resignation_requests_id'), table_name='resignation_requests')
    op.drop_index(op.f('ix_resignation_requests_employee_id'), table_name='resignation_requests')
    op.drop_table('resignation_requests')
    # ### end Alembic commands ###
