""" Phase 9 Expense and Reimbursement

Revision ID: d399fc6f0d4b
Revises: 2e66eb81c306
Create Date: 2026-08-22 15:11:23.186949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd399fc6f0d4b'
down_revision: Union[str, Sequence[str], None] = '2e66eb81c306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_expense_categories_id'), 'expense_categories', ['id'], unique=False)
    op.create_table('expense_claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=False),
    sa.Column('claim_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'MANAGER_APPROVED', 'FINANCE_APPROVED', 'REJECTED', 'SETTLED', name='expensestatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payroll_record_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number')
    )
    op.create_index(op.f('ix_expense_claims_employee_id'), 'expense_claims', ['employee_id'], unique=False)
    op.create_index(op.f('ix_expense_claims_id'), 'expense_claims', ['id'], unique=False)
    op.create_table('expense_audit_trails',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expense_claim_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_claim_id'], ['expense_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_audit_trails_expense_claim_id'), 'expense_audit_trails', ['expense_claim_id'], unique=False)
    op.create_index(op.f('ix_expense_audit_trails_id'), 'expense_audit_trails', ['id'], unique=False)
    op.create_table('expense_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expense_claim_id', sa.String(), nullable=False),
    sa.Column('expense_category_id', sa.String(), nullable=False),
    sa.Column('expense_date', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['expense_claim_id'], ['expense_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_items_expense_claim_id'), 'expense_items', ['expense_claim_id'], unique=False)
    op.create_index(op.f('ix_expense_items_id'), 'expense_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_items_id'), table_name='expense_items')
    op.drop_index(op.f('ix_expense_items_expense_claim_id'), table_name='expense_items')
    op.drop_table('expense_items')
    op.drop_index(op.f('ix_expense_audit_trails_id'), table_name='expense_audit_trails')
    op.drop_index(op.f('ix_expense_audit_trails_expense_claim_id'), table_name='expense_audit_trails')
    op.drop_table('expense_audit_trails')
    op.drop_index(op.f('ix_expense_claims_id'), table_name='expense_claims')
    op.drop_index(op.f('ix_expense_claims_employee_id'), table_name='expense_claims')
    op.drop_table('expense_claims')
    op.drop_index(op.f('ix_expense_categories_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
